name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm test

    # - name: Check test coverage threshold
    #   run: |
    #     COVERAGE=$(npm test | grep -o 'All files[^%]*%' | grep -o '[0-9.]*')
    #     if (( $(echo "$COVERAGE < 70" | bc -l) )); then
    #       echo "Test coverage ($COVERAGE%) is below threshold (70%)"
    #       exit 1
    #     fi

  lint:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: | 
          docker build -t node-github-actions:${{ github.sha }} .

      - name: Copy image to target server and deploy
        run: |
          docker run -d --rm \
            -p 3000:3000 \
            -v /logs:/app/logs \
            --name node-server \
            node-github-actions:${{ github.sha }}